#!/usr/bin/env node
/**
 * Pose maps from OUR rig — the input the image model conditions on.
 *
 * Why this exists (and why it beats feeding third-party screenshots):
 *
 *   • **Legally.** The reference images we study are somebody else's artwork.
 *     Sending them through img2img would produce a derivative of their art.
 *     A *pose* is functional data, not protectable expression — and here the
 *     pose is not even extracted from their pixels: it is generated by our own
 *     `PATTERN_DEMOS` rig, which encodes each movement pattern biomechanically.
 *   • **Correctly.** A diffusion model cannot know that a Nordic curl involves
 *     a fixed shin and a hip-driven descent. Our rig does, because we wrote the
 *     angles. The model only supplies the *look*.
 *   • **Consistently.** Every exercise that shares a pattern gets the identical
 *     silhouette pose, so the set reads as one system rather than 143 unrelated
 *     illustrations.
 *
 * Output: OpenPose-format PNGs (black background, the standard 18-keypoint
 * colour palette), 1024², one per pattern — plus `poses/index.json` mapping every
 * exercise id to its pattern and pose file. Both SD1.5 and SDXL OpenPose
 * ControlNets read this natively, with no preprocessor node needed.
 *
 *   node render-poses.mjs                 # one representative pose per pattern
 *   node render-poses.mjs --all-frames    # every frame (for a future GIF pass)
 *   node render-poses.mjs --contact-sheet # also emit a review sheet (PNG)
 */
import { createRequire } from "node:module";
import { mkdir, readdir, writeFile } from "node:fs/promises";
import path from "node:path";
import { fileURLToPath, pathToFileURL } from "node:url";

const __dirname = path.dirname(fileURLToPath(import.meta.url));
const ROOT = path.resolve(__dirname, "../.."); // fitness-ecosystem/
const OUT = path.join(__dirname, "poses");
const args = process.argv.slice(2);
const allFrames = args.includes("--all-frames");
const contactSheet = args.includes("--contact-sheet");

// ── our data, through the app's own Vite (same aliases as the app) ─────────
async function loadRig() {
  const webRequire = createRequire(path.join(ROOT, "bodylab/apps/web/package.json"));
  const { createServer } = webRequire("vite");
  const server = await createServer({
    root: ROOT,
    configFile: false,
    logLevel: "error",
    server: { middlewareMode: true },
    resolve: {
      alias: { "@fitness/bodylab-exercises": path.join(ROOT, "bodylab/core/exercises/src") },
    },
  });
  try {
    const mod = await server.ssrLoadModule("@fitness/bodylab-exercises");
    const exercises = mod.ALL_EXERCISES.map((e) => ({
      id: e.id,
      name: e.name,
      pattern: mod.getTraits(e.id)?.pattern ?? null,
    }));
    return { demos: mod.PATTERN_DEMOS, exercises };
  } finally {
    await server.close();
  }
}

async function loadChromium() {
  const webRequire = createRequire(path.join(ROOT, "bodylab/apps/web/package.json"));
  for (const pkg of ["@playwright/test", "playwright"]) {
    try {
      const mod = await import(pathToFileURL(webRequire.resolve(pkg)).href);
      const chromium = mod.chromium ?? mod.default?.chromium;
      if (chromium) return chromium;
    } catch {
      /* next candidate */
    }
  }
  throw new Error("no playwright chromium — run `pnpm install` in bodylab/apps/web");
}

/** How long each bone is, in rig units. Proportions tuned to read as a human. */
const BONE = {
  torso: 1.0,
  neck: 0.16,
  head: 0.26,
  thigh: 0.95,
  shin: 0.95,
  upperArm: 0.62,
  foreArm: 0.58,
  foot: 0.3,
};

/** Geometry is done in the page so a single screenshot captures the result. */
const PAGE = `<!doctype html><html><head><meta charset="utf-8"><style>
  html,body{margin:0;background:#000}
  canvas{display:block}
</style></head><body><canvas id="c" width="1024" height="1024"></canvas>
<script>
const BONE = ${JSON.stringify(BONE)};
// The canonical OpenPose-18 palette: ControlNet was trained on exactly these.
const COLOR = {
  nose:[255,0,0], neck:[255,85,0],
  rShoulder:[255,170,0], rElbow:[255,255,0], rWrist:[170,255,0],
  lShoulder:[85,255,0], lElbow:[0,255,0], lWrist:[0,255,85],
  rHip:[0,255,170], rKnee:[0,255,255], rAnkle:[0,170,255],
  lHip:[0,85,255], lKnee:[0,0,255], lAnkle:[85,0,255],
  rEye:[170,0,255], lEye:[255,0,255], rEar:[255,0,170], lEar:[255,0,85],
};
const rad = (d) => (d * Math.PI) / 180;
const add = (a, b, s = 1) => [a[0] + b[0] * s, a[1] + b[1] * s];

/** Rig convention: 0 = straight down, positive = forward (screen +x), y grows down. */
const down = (deg) => [Math.sin(rad(deg)), Math.cos(rad(deg))];
/** Torso convention: 0 = upright, positive = leaning forward. */
const up = (deg) => [Math.sin(rad(deg)), -Math.cos(rad(deg))];

function joints(pose) {
  const side = pose.view !== "front";
  const hip = [0, 0];
  const shoulder = add(hip, up(pose.torso), BONE.torso);
  const neck = add(shoulder, up(pose.torso), BONE.neck);
  const head = add(neck, up(pose.torso), BONE.head);
  const nose = add(head, up(pose.torso), BONE.head * 0.55);

  const knee = add(hip, down(pose.thigh), BONE.thigh);
  const ankle = add(knee, down(pose.shin), BONE.shin);
  const toe = add(ankle, down(pose.foot ?? 90), BONE.foot);

  // Arms: in a side view both arms overlap, so the far one is offset backwards
  // (towards -x) to give the model two readable limbs instead of one.
  const armAngle = pose.arm;
  const foreAngle = pose.forearm ?? pose.arm;
  const elbow = add(shoulder, down(armAngle), BONE.upperArm);
  const wrist = add(elbow, down(foreAngle), BONE.foreArm);
  const farShift = side ? -0.12 : 0;

  const far = (p, i) => [p[0] + farShift, p[1] + (side ? 0 : 0) + (side ? 0.04 * (i % 2) : 0)];

  const out = {
    nose, neck,
    rShoulder: shoulder, rElbow: elbow, rWrist: wrist,
    lShoulder: far(shoulder, 0), lElbow: far(elbow, 1), lWrist: far(wrist, 2),
    rHip: hip, rKnee: knee, rAnkle: ankle,
    // The far leg in a side view: same chain, nudged back so both read.
    lHip: far(hip, 1), lKnee: far(knee, 0), lAnkle: far(ankle, 1),
  };
  // Eyes/ears: a rough face reading in the torso's facing direction.
  const face = up(pose.torso);
  const perp = [-face[1], face[0]];
  out.rEye = add(add(head, face, 0.02), perp, 0.05);
  out.lEye = add(add(head, face, 0.02), perp, -0.05);
  out.rEar = add(head, perp, 0.12);
  out.lEar = add(head, perp, -0.12);
  out.toe = toe;
  return { pts: out, ground: Math.max(ankle[1], toe[1]) };
}

/** Front view: the same chain, but the spread parameters open the limbs sideways. */
function frontJoints(pose) {
  const spread = rad(pose.spread ?? 8);
  const legSpread = rad(pose.legSpread ?? 6);
  const hipC = [0, 0];
  const shoulder = add(hipC, up(pose.torso), BONE.torso);
  const neck = add(shoulder, up(pose.torso), BONE.neck);
  const head = add(neck, up(pose.torso), BONE.head);
  const nose = add(head, up(pose.torso), BONE.head * 0.55);
  const pts = { nose, neck };
  const sideOf = (s) => (s === "r" ? 1 : -1);
  for (const s of ["r", "l"]) {
    const k = sideOf(s);
    const sh = add(shoulder, [1, 0], 0.22 * k);
    const el = add(sh, [Math.sin(spread) * k, Math.cos(spread)], BONE.upperArm);
    const wr = add(el, [Math.sin(spread * 0.75) * k, Math.cos(spread * 0.75)], BONE.foreArm);
    const hp = add(hipC, [1, 0], 0.16 * k);
    const kn = add(hp, [Math.sin(legSpread) * k, Math.cos(legSpread)], BONE.thigh);
    const an = add(kn, [Math.sin(legSpread * 0.4) * k, Math.cos(legSpread * 0.4)], BONE.shin);
    // Plain concatenation, not template literals: this whole function is
    // inside one big template string and nested backticks would end it.
    pts[s + "Shoulder"] = sh;
    pts[s + "Elbow"] = el;
    pts[s + "Wrist"] = wr;
    pts[s + "Hip"] = hp;
    pts[s + "Knee"] = kn;
    pts[s + "Ankle"] = an;
    pts[s + "Eye"] = add(add(head, up(pose.torso), 0.02), [1, 0], 0.05 * k);
    pts[s + "Ear"] = add(head, [1, 0], 0.12 * k);
  }
  const lowest = Math.max(pts.rAnkle[1], pts.lAnkle[1]);
  return { pts, ground: lowest };
}

const BONES = [
  ["neck", "rShoulder"], ["rShoulder", "rElbow"], ["rElbow", "rWrist"],
  ["neck", "lShoulder"], ["lShoulder", "lElbow"], ["lElbow", "lWrist"],
  ["neck", "rHip"], ["rHip", "rKnee"], ["rKnee", "rAnkle"],
  ["neck", "lHip"], ["lHip", "lKnee"], ["lKnee", "lAnkle"],
  ["neck", "nose"], ["nose", "rEye"], ["nose", "lEye"],
  ["rEye", "rEar"], ["lEye", "lEar"],
];
const JOINT_COLOR = {
  nose: "nose", neck: "neck",
  rShoulder: "rShoulder", rElbow: "rElbow", rWrist: "rWrist",
  lShoulder: "lShoulder", lElbow: "lElbow", lWrist: "lWrist",
  rHip: "rHip", rKnee: "rKnee", rAnkle: "rAnkle",
  lHip: "lHip", lKnee: "lKnee", lAnkle: "lAnkle",
  rEye: "rEye", lEye: "lEye", rEar: "rEar", lEar: "lEar",
};

window.__drawPose = (pose) => {
  const c = document.getElementById("c");
  const g = c.getContext("2d");
  g.fillStyle = "#000";
  g.fillRect(0, 0, c.width, c.height);

  const { pts, ground } = pose.view === "front" ? frontJoints(pose) : joints(pose);
  const all = Object.values(pts);
  if (pts.rAnkle) all.push([pts.rAnkle[0], ground]);

  const xs = all.map((p) => p[0]);
  const ys = all.map((p) => p[1]);
  const minX = Math.min(...xs), maxX = Math.max(...xs);
  const minY = Math.min(...ys), maxY = Math.max(...ys);
  const pad = 0.14;
  const scale = Math.min(
    (c.width * (1 - 2 * pad)) / Math.max(0.4, maxX - minX),
    (c.height * (1 - 2 * pad)) / Math.max(0.4, maxY - minY)
  );
  const offX = (c.width - (maxX + minX) * scale) / 2;
  const offY = (c.height - (maxY + minY) * scale) / 2;
  const T = (p) => [p[0] * scale + offX, p[1] * scale + offY];

  // Ground line, when the pattern stands on the floor — it anchors the model.
  if (pose.ground) {
    const y = ground * scale + offY;
    g.strokeStyle = "#1e1e1e";
    g.lineWidth = 8;
    g.beginPath();
    g.moveTo(0, y);
    g.lineTo(c.width, y);
    g.stroke();
  }

  const paint = (p, w) => {
    const a = T(p[0]), b = T(p[1]);
    g.lineWidth = w;
    g.lineCap = "round";
    g.strokeStyle = "rgba(255,255,255,0.92)";
    g.beginPath();
    g.moveTo(a[0], a[1]);
    g.lineTo(b[0], b[1]);
    g.stroke();
  };

  // Limbs: the canonical colours, width relative to the bone length.
  // Each entry of pts is already a point — pass it on unchanged (the first
  // version re-indexed it, so every path was NaN: an invisible skeleton while
  // the ground line still showed up, which is how the pixel check caught it).
  for (const [a, b] of BONES) {
    if (!pts[a] || !pts[b]) continue;
    const col = COLOR[JOINT_COLOR[b]] ?? COLOR.neck;
    const A = T(pts[a]), B = T(pts[b]);
    g.strokeStyle = \`rgb(\${col[0]},\${col[1]},\${col[2]})\`;
    g.lineWidth = 22;
    g.lineCap = "round";
    g.beginPath();
    g.moveTo(A[0], A[1]);
    g.lineTo(B[0], B[1]);
    g.stroke();
  }
  // Joints.
  for (const [name, p] of Object.entries(pts)) {
    const col = COLOR[JOINT_COLOR[name]];
    if (!col) continue;
    const P = T(p);
    g.fillStyle = \`rgb(\${col[0]},\${col[1]},\${col[2]})\`;
    g.beginPath();
    g.arc(P[0], P[1], name === "neck" || name === "nose" ? 16 : 11, 0, Math.PI * 2);
    g.fill();
  }
  return true;
};
</script></body></html>`;

const rig = await loadRig();
const chromium = await loadChromium();
await mkdir(OUT, { recursive: true });

const browser = await chromium.launch();
const page = await browser.newPage({ viewport: { width: 1024, height: 1024 } });
await page.setContent(PAGE);

const index = { patterns: {}, exercises: {}, generator: "tools/ai-media/render-poses.mjs" };
let rendered = 0;

for (const [pattern, demo] of Object.entries(rig.demos)) {
  const poses = allFrames
    ? demo.frames.map((f, i) => ({ f, i }))
    : [{ f: demo.frames[Math.floor(demo.frames.length / 2)], i: 0 }];
  const files = [];
  for (const { f, i } of poses) {
    const pose = {
      ...f,
      view: demo.view,
      ground: demo.ground,
      rank: i,
    };
    await page.evaluate((p) => window.__drawPose(p), pose);
    const name = allFrames ? `${pattern}-f${i}.png` : `${pattern}.png`;
    await page.locator("canvas").screenshot({ path: path.join(OUT, name) });
    files.push(name);
    rendered++;
  }
  index.patterns[pattern] = {
    view: demo.view,
    anchor: demo.anchor,
    watch: demo.watch,
    frames: files,
  };
  console.log(`  ✎ ${pattern.padEnd(22)} → ${files.join(", ")}`);
}

let unmapped = 0;
for (const e of rig.exercises) {
  index.exercises[e.id] = { pattern: e.pattern, pose: e.pattern ? index.patterns[e.pattern]?.frames[0] : null };
  if (!e.pattern || !index.patterns[e.pattern]) unmapped++;
}

await writeFile(path.join(OUT, "index.json"), JSON.stringify(index, null, 2));
await browser.close();

console.log(`\n${rendered} pose maps in ${path.relative(ROOT, OUT)}`);
console.log(`${rig.exercises.length - unmapped}/${rig.exercises.length} exercises mapped to a pattern`);
if (unmapped) console.log(`⚠ ${unmapped} exercises have no pattern/pose — they keep the drawn fallback for now`);

if (contactSheet) {
  const files = (await readdir(OUT)).filter((f) => f.endsWith(".png"));
  const html = `<html><body style="background:#000;color:#f97316;font:13px system-ui;display:grid;grid-template-columns:repeat(6,1fr);gap:8px">
    ${files.map((f) => `<figure style="margin:0"><img src="${f}" style="width:100%"><figcaption>${f}</figcaption></figure>`).join("")}
  </body></html>`;
  await writeFile(path.join(OUT, "contact-sheet.html"), html);
  console.log("contact sheet: open tools/ai-media/poses/contact-sheet.html");
}
