/**
 * Traits for the expansion catalog (see `./catalog-expansion`).
 *
 * Kept in its own module so the merge in `./traits` stays a one-liner and there
 * is no import cycle: this file only ever imports the *type* (`import type` is
 * erased at compile time), and defines its own local `t()` helper instead of
 * reaching for the one in `./traits`. That matters — a cycle here would be a
 * temporal-dead-zone crash at import, and this package is imported by both apps.
 *
 * Hard rules the test suite enforces on every entry below:
 *   - `requires` is a list of OR-groups that are ANDed; `[]` means bodyweight;
 *   - every capability named exists in `./equipment` presets;
 *   - a `cardio` category entry is time-loaded and declares steady/interval;
 *   - an exercise whose equipment label starts with "Bodyweight" requires
 *     nothing at all (so the label and the gate can never disagree).
 *
 * @module traits-expansion
 */

import type { ExerciseTraits } from "./traits";

const t = (traits: ExerciseTraits): ExerciseTraits => traits;

export const EXPANSION_TRAITS: Record<string, ExerciseTraits> = {
  // ── Push ─────────────────────────────────────────────────────────────────
  "dumbbell-floor-press": t({
    requires: [["dumbbell"]],
    pattern: "horizontal_push",
    loadType: "dumbbell",
    unilateral: false,
    jointStress: 1,
    spineLoad: 1,
    progression: ["load", "reps", "tempo"],
    setupMin: 1,
  }),
  "deficit-push-up": t({
    requires: [],
    pattern: "horizontal_push",
    loadType: "bodyweight",
    unilateral: false,
    jointStress: 2,
    spineLoad: 1,
    progression: ["reps", "range", "leverage"],
    setupMin: 1,
  }),
  "decline-push-up": t({
    requires: [],
    pattern: "horizontal_push",
    loadType: "bodyweight",
    unilateral: false,
    jointStress: 2,
    spineLoad: 1,
    progression: ["reps", "leverage", "range"],
    setupMin: 0,
  }),
  "pseudo-planche-push-up": t({
    requires: [],
    pattern: "horizontal_push",
    loadType: "bodyweight",
    unilateral: false,
    jointStress: 3,
    spineLoad: 1,
    progression: ["leverage", "reps", "range"],
    setupMin: 0,
  }),
  "archer-push-up": t({
    requires: [],
    pattern: "horizontal_push",
    loadType: "bodyweight",
    unilateral: true,
    jointStress: 3,
    spineLoad: 1,
    progression: ["reps", "leverage", "volume"],
    setupMin: 0,
  }),
  "dumbbell-squeeze-press": t({
    requires: [["dumbbell"]],
    pattern: "horizontal_push",
    loadType: "dumbbell",
    unilateral: false,
    jointStress: 1,
    spineLoad: 1,
    progression: ["load", "reps"],
    setupMin: 0,
  }),
  "seated-dumbbell-press": t({
    requires: [["dumbbell"], ["bench", "box"]],
    pattern: "vertical_push",
    loadType: "dumbbell",
    unilateral: false,
    jointStress: 2,
    spineLoad: 1,
    progression: ["load", "reps"],
    setupMin: 1,
  }),
  "dumbbell-front-raise": t({
    requires: [["dumbbell"]],
    pattern: "shoulder_flexion",
    loadType: "dumbbell",
    unilateral: false,
    jointStress: 2,
    spineLoad: 1,
    progression: ["load", "tempo", "reps"],
    setupMin: 0,
  }),
  "dumbbell-upright-row": t({
    requires: [["dumbbell"]],
    pattern: "shoulder_abduction",
    loadType: "dumbbell",
    unilateral: false,
    // Impingement-prone by nature: the planner keeps it out of tired-shoulder days.
    jointStress: 3,
    spineLoad: 1,
    progression: ["load", "reps", "range"],
    setupMin: 0,
  }),
  "band-overhead-press": t({
    requires: [["bands"]],
    pattern: "vertical_push",
    loadType: "band",
    unilateral: false,
    jointStress: 1,
    spineLoad: 1,
    progression: ["reps", "tempo", "volume"],
    setupMin: 0,
  }),
  "kettlebell-push-press": t({
    requires: [["kettlebell"]],
    pattern: "vertical_push",
    loadType: "kettlebell",
    unilateral: false,
    jointStress: 2,
    spineLoad: 2,
    progression: ["load", "reps", "volume"],
    setupMin: 0,
  }),
  "wall-handstand-push-up": t({
    requires: [],
    pattern: "vertical_push",
    loadType: "bodyweight",
    unilateral: false,
    jointStress: 3,
    spineLoad: 2,
    progression: ["leverage", "reps", "range"],
    setupMin: 1,
  }),

  // ── Pull ─────────────────────────────────────────────────────────────────
  "assisted-pull-up": t({
    requires: [["pullup_bar", "rings"], ["bands"]],
    pattern: "vertical_pull",
    loadType: "bodyweight",
    unilateral: false,
    jointStress: 2,
    spineLoad: 1,
    progression: ["leverage", "reps", "volume"],
    setupMin: 1,
  }),
  "band-lat-pulldown": t({
    requires: [["bands"]],
    pattern: "vertical_pull",
    loadType: "band",
    unilateral: false,
    jointStress: 1,
    spineLoad: 1,
    progression: ["reps", "tempo", "volume"],
    setupMin: 1,
  }),
  "inverted-row-feet-elevated": t({
    requires: [["dip_bars", "rings"]],
    pattern: "horizontal_pull",
    loadType: "bodyweight",
    unilateral: false,
    jointStress: 2,
    spineLoad: 1,
    progression: ["leverage", "reps", "volume"],
    setupMin: 1,
  }),
  "dumbbell-renegade-row": t({
    requires: [["dumbbell"]],
    pattern: "horizontal_pull",
    loadType: "dumbbell",
    unilateral: true,
    jointStress: 2,
    spineLoad: 2,
    progression: ["load", "reps", "tempo"],
    setupMin: 1,
  }),
  "chest-supported-dumbbell-row": t({
    requires: [["dumbbell"], ["bench"]],
    pattern: "horizontal_pull",
    loadType: "dumbbell",
    unilateral: false,
    jointStress: 1,
    spineLoad: 1,
    progression: ["load", "reps"],
    setupMin: 1,
  }),
  "straight-arm-pulldown": t({
    requires: [["cable"]],
    pattern: "shoulder_extension",
    loadType: "cable",
    unilateral: false,
    jointStress: 2,
    spineLoad: 1,
    progression: ["load", "reps", "tempo"],
    setupMin: 1,
  }),
  "kettlebell-row": t({
    requires: [["kettlebell"]],
    pattern: "horizontal_pull",
    loadType: "kettlebell",
    unilateral: true,
    jointStress: 1,
    spineLoad: 2,
    progression: ["load", "reps"],
    setupMin: 0,
  }),
  "dead-hang": t({
    requires: [["pullup_bar", "rings"]],
    pattern: "carry",
    loadType: "bodyweight",
    unilateral: false,
    jointStress: 2,
    spineLoad: 1,
    progression: ["time", "volume"],
    setupMin: 0,
  }),

  // ── Arms ─────────────────────────────────────────────────────────────────
  "dumbbell-curl": t({
    requires: [["dumbbell"]],
    pattern: "elbow_flexion",
    loadType: "dumbbell",
    unilateral: false,
    jointStress: 1,
    spineLoad: 1,
    progression: ["load", "reps", "tempo"],
    setupMin: 0,
  }),
  "concentration-curl": t({
    requires: [["dumbbell"]],
    pattern: "elbow_flexion",
    loadType: "dumbbell",
    unilateral: true,
    jointStress: 1,
    spineLoad: 1,
    progression: ["load", "reps", "tempo"],
    setupMin: 0,
  }),
  "spider-curl": t({
    requires: [["dumbbell"], ["bench"]],
    pattern: "elbow_flexion",
    loadType: "dumbbell",
    unilateral: false,
    jointStress: 1,
    spineLoad: 1,
    progression: ["load", "reps", "tempo"],
    setupMin: 1,
  }),
  "incline-hammer-curl": t({
    requires: [["dumbbell"], ["bench"]],
    pattern: "elbow_flexion",
    loadType: "dumbbell",
    unilateral: false,
    jointStress: 1,
    spineLoad: 1,
    progression: ["load", "reps"],
    setupMin: 1,
  }),
  "band-overhead-triceps-extension": t({
    requires: [["bands"]],
    pattern: "elbow_extension",
    loadType: "band",
    unilateral: false,
    jointStress: 2,
    spineLoad: 1,
    progression: ["reps", "tempo", "volume"],
    setupMin: 1,
  }),
  "tate-press": t({
    requires: [["dumbbell"]],
    pattern: "elbow_extension",
    loadType: "dumbbell",
    unilateral: false,
    jointStress: 2,
    spineLoad: 1,
    progression: ["load", "reps", "tempo"],
    setupMin: 0,
  }),

  // ── Legs ─────────────────────────────────────────────────────────────────
  "dumbbell-split-squat": t({
    requires: [["dumbbell"]],
    pattern: "lunge",
    loadType: "dumbbell",
    unilateral: true,
    jointStress: 2,
    spineLoad: 1,
    progression: ["load", "reps", "range"],
    setupMin: 1,
  }),
  "reverse-lunge": t({
    requires: [],
    pattern: "lunge",
    loadType: "bodyweight",
    unilateral: true,
    jointStress: 2,
    spineLoad: 1,
    progression: ["reps", "leverage", "volume"],
    setupMin: 0,
  }),
  "walking-lunge": t({
    requires: [],
    pattern: "lunge",
    loadType: "bodyweight",
    unilateral: true,
    jointStress: 2,
    spineLoad: 1,
    progression: ["reps", "volume", "range"],
    setupMin: 0,
  }),
  "pistol-squat": t({
    requires: [],
    pattern: "squat",
    loadType: "bodyweight",
    unilateral: true,
    jointStress: 3,
    spineLoad: 1,
    progression: ["leverage", "reps", "range"],
    setupMin: 0,
  }),
  "sissy-squat": t({
    requires: [],
    pattern: "knee_extension",
    loadType: "bodyweight",
    unilateral: false,
    // Puts real shear through the knee: high joint stress, zero spinal load.
    jointStress: 3,
    spineLoad: 1,
    progression: ["reps", "range", "tempo"],
    setupMin: 0,
  }),
  "glute-bridge": t({
    requires: [],
    pattern: "hip_extension",
    loadType: "bodyweight",
    unilateral: false,
    jointStress: 1,
    spineLoad: 1,
    progression: ["reps", "leverage", "volume"],
    setupMin: 0,
  }),
  "single-leg-glute-bridge": t({
    requires: [],
    pattern: "hip_extension",
    loadType: "bodyweight",
    unilateral: true,
    jointStress: 1,
    spineLoad: 1,
    progression: ["leverage", "reps", "volume"],
    setupMin: 0,
  }),
  "cable-glute-kickback": t({
    requires: [["cable"]],
    pattern: "hip_extension",
    loadType: "cable",
    unilateral: true,
    jointStress: 1,
    spineLoad: 1,
    progression: ["load", "reps", "tempo"],
    setupMin: 1,
  }),
  "good-morning": t({
    requires: [["barbell"]],
    pattern: "hinge",
    loadType: "barbell",
    unilateral: false,
    jointStress: 2,
    spineLoad: 3,
    progression: ["load", "reps", "tempo"],
    setupMin: 2,
  }),
  "kettlebell-swing": t({
    requires: [["kettlebell"]],
    pattern: "hinge",
    loadType: "kettlebell",
    unilateral: false,
    jointStress: 1,
    spineLoad: 2,
    progression: ["load", "volume", "tempo"],
    setupMin: 0,
  }),
  "box-jump": t({
    requires: [["box"]],
    pattern: "squat",
    loadType: "bodyweight",
    unilateral: false,
    jointStress: 3,
    spineLoad: 2,
    progression: ["leverage", "reps"],
    setupMin: 1,
  }),
  "donkey-calf-raise": t({
    requires: [["bench"]],
    pattern: "plantar_flexion",
    loadType: "bodyweight",
    unilateral: false,
    jointStress: 1,
    spineLoad: 1,
    progression: ["reps", "range", "tempo"],
    setupMin: 1,
  }),

  // ── Core ─────────────────────────────────────────────────────────────────
  "hanging-knee-raise": t({
    requires: [["pullup_bar", "rings"]],
    pattern: "core_flexion",
    loadType: "bodyweight",
    unilateral: false,
    jointStress: 2,
    spineLoad: 1,
    progression: ["reps", "range", "tempo"],
    setupMin: 0,
  }),
  "hollow-rock": t({
    requires: [],
    pattern: "core_flexion",
    loadType: "bodyweight",
    unilateral: false,
    jointStress: 1,
    spineLoad: 1,
    progression: ["time", "leverage", "volume"],
    setupMin: 0,
  }),
  "v-up": t({
    requires: [],
    pattern: "core_flexion",
    loadType: "bodyweight",
    unilateral: false,
    jointStress: 2,
    spineLoad: 2,
    progression: ["reps", "tempo", "range"],
    setupMin: 0,
  }),
  "bird-dog": t({
    requires: [],
    pattern: "core_anti_extension",
    loadType: "bodyweight",
    unilateral: true,
    jointStress: 1,
    spineLoad: 1,
    progression: ["time", "reps"],
    setupMin: 0,
  }),
  "pallof-press": t({
    requires: [["bands", "cable"]],
    pattern: "core_anti_lateral",
    loadType: "band",
    unilateral: true,
    jointStress: 1,
    spineLoad: 1,
    progression: ["load", "time", "reps"],
    setupMin: 1,
  }),
  "sit-up": t({
    requires: [],
    pattern: "core_flexion",
    loadType: "bodyweight",
    unilateral: false,
    jointStress: 2,
    spineLoad: 2,
    progression: ["reps", "tempo", "volume"],
    setupMin: 0,
  }),

  // ── Cardio (category cardio ⇒ time-loaded + steady/interval) ─────────────
  "shadow-boxing-intervals": t({
    requires: [],
    pattern: "cardio_interval",
    loadType: "time",
    unilateral: false,
    jointStress: 1,
    spineLoad: 1,
    progression: ["time", "volume"],
    setupMin: 0,
    cardio: "interval",
  }),
  "tabata-bodyweight": t({
    requires: [],
    pattern: "cardio_interval",
    loadType: "time",
    unilateral: false,
    jointStress: 2,
    spineLoad: 1,
    progression: ["time", "volume"],
    setupMin: 0,
    cardio: "interval",
  }),
  "jump-rope-steady": t({
    requires: [["jump_rope"]],
    pattern: "cardio_steady",
    loadType: "time",
    unilateral: false,
    jointStress: 2,
    spineLoad: 1,
    progression: ["time", "volume"],
    setupMin: 1,
    cardio: "steady",
  }),
  "bike-sprint-intervals": t({
    requires: [["bike"]],
    pattern: "cardio_interval",
    loadType: "time",
    unilateral: false,
    jointStress: 1,
    spineLoad: 1,
    progression: ["time", "volume"],
    setupMin: 1,
    cardio: "interval",
  }),
  "stair-climb-steady": t({
    requires: [["stairs"]],
    pattern: "cardio_steady",
    loadType: "time",
    unilateral: false,
    jointStress: 2,
    spineLoad: 1,
    progression: ["time", "volume"],
    setupMin: 0,
    cardio: "steady",
  }),

  // ── Symmetry import gaps (2026-10-04) ───────────────────────────────────
  crunch: t({
    requires: [],
    pattern: "core_flexion",
    loadType: "bodyweight",
    unilateral: false,
    jointStress: 2,
    spineLoad: 2,
    progression: ["reps", "tempo", "volume"],
    setupMin: 0,
  }),
  "decline-crunch": t({
    requires: [["bench"]],
    pattern: "core_flexion",
    loadType: "bodyweight",
    unilateral: false,
    jointStress: 2,
    spineLoad: 2,
    progression: ["reps", "tempo"],
    setupMin: 1,
  }),
  "oblique-crunch": t({
    requires: [["dumbbell"]],
    pattern: "core_rotation",
    loadType: "dumbbell",
    unilateral: false,
    jointStress: 1,
    spineLoad: 1,
    progression: ["load", "reps"],
    setupMin: 0,
  }),
  "dumbbell-shrugs": t({
    requires: [["dumbbell"]],
    pattern: "horizontal_pull",
    loadType: "dumbbell",
    unilateral: false,
    jointStress: 1,
    spineLoad: 1,
    progression: ["load", "reps"],
    setupMin: 1,
  }),
  "tricep-kickback": t({
    requires: [["cable"]],
    pattern: "elbow_extension",
    loadType: "cable",
    unilateral: false,
    jointStress: 1,
    spineLoad: 1,
    progression: ["load", "reps"],
    setupMin: 1,
  }),
  "wrist-roller": t({
    requires: [["dumbbell"]],
    pattern: "forearm_flexion",
    loadType: "dumbbell",
    unilateral: false,
    jointStress: 2,
    spineLoad: 1,
    progression: ["load", "time"],
    setupMin: 1,
  }),
  "hip-abduction-machine": t({
    requires: [["machines"]],
    pattern: "hip_abduction",
    loadType: "machine",
    unilateral: false,
    jointStress: 1,
    spineLoad: 1,
    progression: ["load", "reps"],
    setupMin: 1,
  }),
  "hip-adduction-machine": t({
    requires: [["machines"]],
    pattern: "hip_adduction",
    loadType: "machine",
    unilateral: false,
    jointStress: 1,
    spineLoad: 1,
    progression: ["load", "reps"],
    setupMin: 1,
  }),
};
